baseURL = "localhost:1313"
languageCode = "en-us"
title = "Home"
theme = "influencer hugo"
summaryLength = "10"
paginate = 6
themesDir = "themes"
publishDir = "public"

[params]
  logo = "https://authortodd.b-cdn.net/logo.png"
  home = "Home"
  description = "Test"
  author = ""
  googleAnalitycsID = ""
  copyright = "Powered by [Dark Matter](www.darkmatter.works) and Compassio Veraque."

[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
URL = "plugins/slick/slick.css"

[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"

[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"

[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"

[[params.plugins.js]]
URL = "plugins/magnific-popup/magnific-popup.min.js"

  [params.preloader]
  enable = true
  preloader = ""

  [params.navButton]
  enable = true

  [params.cookies]
  enable = true
  expire_days = 2

  [params.footer]
  content = "There's nothing Todd enjoys more than hearing from readers."

  [[params.share]]
  title = "facebook"
  icon = "ti-facebook"
  link = "#"

  [[params.share]]
  title = "twitter"
  icon = "ti-twitter-alt"
  link = "#"

  [[params.share]]
  title = "linkedin"
  icon = "ti-linkedin"
  link = ""

[[menu.main]]
name = "Books"
URL = "otherBooks"
weight = 1

[[menu.main]]
name = "Events"
URL = "blog"
weight = 2

[[menu.main]]
name = "Reviews"
URL = "review"
weight = 3

[[menu.main]]
name = "About"
URL = "author"
weight = 4

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5
